const EventList = [
  {
    id: 1,
    url: "https://www.gjcity.go.kr/common/file/img/view.do?atchFileId=7cb33757806545ceaaca239dfcb42e808165ac9519c9f655026eee5af335d36f&fileSn=c30044f361fa6d122d6b3ca447a95ac9&width=&height=",
    web: "https://www.gjcity.go.kr/tour/tomato/main.do?mId=0203010000&token=1781026720706",
    title: "퇴촌 토마토 축제",
    region: "서울/경기/인천",
    startDate: "2026.06.19",
    endDate: "2026.06.21",
    time: "09:00 ~ 18:00",
    num: " 031-887-3893",
    location: "광주시 퇴촌면 광동로",
    fee: "무료",
    desc: "금빛 모래 땅에서 자라나 당도가 높고 아삭한 여주 금사 참외의 첫 수확을 알리는 축제입니다. 현장 할인 판매와 참외 화분 만들기 등 가족 체험이 가득합니다."
  },

  {
    id: 2,
    url: "https://cdn.imweb.me/thumbnail/20260521/327ceda46d3c9.png",
    web: "https://watermelonfestival.kr/",
    title: "양평 수박 축제",
    region: "서울/경기/인천",
    startDate: "2026.07.04",
    endDate: "2026.07.05",
    time: "상시 운영",
    num: " 021-770-3226",
    location: "경기도 양평군 청운면 용두로 170",
    fee: "프로그램별 상이",
    desc: "물 맑은 양평의 대표 특산물, 당도 높은 청운 수박을 직접 수확하고 시원한 수박 화채를 만들어 보는 한여름의 패밀리 축제입니다.",
    program: [
        "수박카빙",
        "가족조각대회",
        "가요제",
    ]
  },
  {
    id: 3,
    url: "http://www.jcwpeach.kr/_data/file/bbsData/52c89e499b6d0b2694f86e4a3a18907e.jpg",
    web: "http://www.jcwpeach.kr/",
    title: "세종 조치원 복숭아 축제",
    region: "충청",
    startDate: "2026.07.24",
    endDate: "2026.07.26",
    time: "상시 운영",
    num: " 044-300-2512",
    location: "세종특별자치시 조치원읍 대첩로 98",
    fee: "무료 (체험비 별도)",
    desc: "100년 전통의 조치원 복숭아의 싱싱한 맛을 전하는 여름 대표 축제입니다. 싱그러운 복숭아 수확과 복숭아 디저트 만들기 체험을 제공합니다.",
    program: [
        "블랙이글스 에어쇼",
        "복숭아 떡 길게 뽑기",
        "화채 나눔 행사",
        "주요 내빈 축사",
        "복숭아 홍보판매장",
        "복숭아 굿즈몰",
        "복숭아 드레스코드 이벤트관",
        "복숭아 디저트 페어(15개소), 먹거리(10종)",
        "복숭아 포토존",
        "복숭아 수확 체험",
      ]
  },
  {
    id: 4,
    url: "https://www.oc.go.kr/DATA/contents/main/20250630051143422_L6Ub.jpg",
    web: "https://www.oc.go.kr/tour/contents.do?key=2732",
    title: "향수옥천 포도, 복숭아 축제",
    region: "충청",
    startDate: "2026.07.31",
    endDate: "2026.08.02",
    time: "09:00 ~ 18:00",
    num: " 043-730-3842",
    location: "충북 옥천군 옥천읍 옥천공설운동장 일원",
    fee: "무료",
    desc: "대청호반 청정지역인 옥천에서 새콤달콤한 포도와 복숭아가 탐스럽게 익어가는 계절에 향수옥천 포도·복숭아축제장에서 여러분을 기다리겠습니다.",
    program: [
        "포도복숭아 판매",
        "체험, 홍보",
        "향수상회",
        "푸드트럭",
        "품종, 역사전시",
        "귀농귀촌/재배상담",
        "플리마켓",
      ]
  },
  {
    id: 5,
    url: "https://www.gcpodo.com/img/main/poster.png",
    web: "https://www.gcpodo.com/",
    title: "김천 포도 축제",
    region: "경상",
    startDate: "2026.08.14",
    endDate: "2026.08.16",
    time: "10:00 ~ 17:00",
    num: "054-421-2532",
    location: "경상북도 김천시 운동장길 1 김천종합스포츠타운 보조경기장 일원",
    fee: "무료 (수확체험비 별도)",
    desc: "꿈이 있는 김천 포도와 함께하는 새콤달콤한 추억 여행! 포도 따기 체험 농장 운영 및 포도 밟기 등 다채로운 오감 만족 체험이 열립니다.",
    program: [
        "축하 공연",
        "샤인 빌리지",
        "키즈 체험 빌리지",
        "키즈 체험 빌리지",
        "시니어 체험 빌리지",
        "포도 디저트 카페",
        "와인 빌리지",
      ]
  },
  {
    id: 6,
    url: "https://csapplefestival.kr/theme/webon01/img/infomation_img01-3.jpg",
    web: "https://csapplefestival.kr/index.php",
    title: "청송 사과 축제",
    region: "경상",
    startDate: "2026.11.04",
    endDate: "2026.11.08",
    time: "09:00 ~ 18:00",
    num: "054-870-6237",
    location: "청송읍 용전천 현비암 일원",
    fee: "무료",
    desc: "대한민국 최고 브랜드 청송사과의 우수성을 널리 알리는 축제입니다. 사과 껍질 길게 깎기, 사과 선별 체험 등 남녀노소 즐길 거리가 가득합니다.",
    program: [
        "꿀잼 사과난타(스트레스를 날려라)",
        "도전 사과선별 로또",
        "만유인력 황금사과를 찾아라",
        "청송사과 꽃줄엮기 전국대회",
        "청송사과 퍼레이드",
        "원산지 표시위반자 의금부 압송",
        "사과 올림픽"
      ]
  },
  {
    id: 7,
    url: "https://jangsufestival.com/img/intro/intro_2026_jangsu.jpg",
    web: "https://www.jangsufestival.com/index.php#",
    title: "장수한우랑사과랑축제",
    region: "전라",
    startDate: "2026.09.10",
    endDate: "2026.09.13",
    time: "10:00 ~ 21:00",
    num:"063-350-2350",
    location: "전북 장수군 장수읍 의암공원 일원",
    fee: "무료",
    desc: "청정 자연 장수군에서 펼쳐지는 명품 한우와 새콤달콤 아삭한 사과의 맛있는 만남! 다양한 수확 체험과 시식 행사가 준비되어 있습니다.",
    program: [
        "레드푸드 요리만들기 체험",
        "레드푸드 사찰 음식만들기 체험",
        "아빠와 함께 장수토마토 스파게티 만들기",
        "레드푸드를 찾아라",
        "장수 이츠레드 푸드 체험",
        "전국 한우곤포 나르기대회",
    ]
  },
  {
    id: 8,
    url: "https://static.wixstatic.com/media/55de1c_88667859f84b47cab1503c8b0e9df0f3~mv2.jpg/v1/fill/w_1418,h_1995,al_c,q_90,enc_avif,quality_auto/KakaoTalk_20260508_164500174.jpg",
    web: "https://www.xn--jj0bn76ahhehyg.com/",
    title: "금사 참외 축제",
    region: "서울/경기/인천",
    startDate: "2026.05.22",
    endDate: "2026.05.24",
    time: "09:00 ~ 18:00",
    num:"031-887-3893",
    location: "경기도 여주시 금사면 이여로 1278",
    fee: "무료",
    desc: "금빛 모래 땅에서 자라나 당도가 높고 아삭한 여주 금사 참외의 첫 수확을 알리는 축제입니다. 현장 할인 판매와 참외 화분 만들기 등 가족 체험이 가득합니다.",
    program: [
      "참외 진 기록 게임",
        "참외밭으로 떠나는 금빛 여행",
        "여주금사 예술 가요제",
        "참외 판매관",
        "먹거리 마당",
        "화채나눔이벤트",
        "가족 놀이 체험",
        "금사 참외 축제 노래자랑",
    ]
  },
];

export default EventList;